# Docker Compose
spring.docker.compose.skip.in-tests=false

# Users service
service.users.server=http://localhost
service.users.port=8082
service.users.username=admin
service.users.password=aW3s0m3

# MongoDB
spring.data.mongodb.uuid-representation=standard
spring.data.mongodb.database=retrodb
spring.data.mongodb.repositories.type=reactive